#!/usr/bin/env bash

TIME=0
sleep 4
echo "Starting"

while true; do 
  xdotool key w
  TIME=$(shuf -i 140-160 -n 1)
  sleep $((TIME / 100));

  xdotool key space
  sleep $(shuf -i 30-35 -n 1);
done;



