#!/usr/bin/env bash

TIME=0
sleep 4
echo "Starting"

# Saved for smelting
while true; do 
  xdotool click 1
  TIME=$(shuf -i 150-180 -n 1)
  sleep $(($TIME / 100));

  xdotool key space
  sleep $(shuf -i 104-110 -n 1);
done;



